### ISSUE TITLE
Require test account details for login to the app.

### ISSUE THREAD

**Issue by SatishBV** [crux-bphc/CMS-iOS#95]
Installed the app but got stuck at login. If there is any test account that is being used to login, it would be great to mention it in the documentation.

**Comment by SatishBV** [comment]
In addition to that, if I can login somehow, I would get _wstoken_ , _courseId_ etc. which are being used in the APIs. Currently, I am able to import the collection into Postman but without some of these params, I am unable to fetch any response. 

I believe I can make the BackgroundFetch.swift file much simpler by using Codable protocol. But first, I need to take a look at the response to understand how to parse it.

@punss Plz help.

**Comment by punss** [comment]
@SatishBV I have emailed the credentials for the test account to the email mentioned on your GitHub page.
